cargo-features = ["profile-rustflags"]

[package]
name = "smalloc"
version = "0.1.2"
edition = "2024"

[dependencies]
bytesize = "1.3.2"
rand = "0.9.0"
rand_distr = "0.5.0"
rustix = { version = "1.0.2", features = ["mm"] }

[profile.release]
lto = "fat"
rustflags = ["-C", "target-cpu=native"]
