cargo-features = ["profile-rustflags"]

[package]
name = "smalloc"
version = "0.1.2"
edition = "2024"

[dependencies]
atomic-dbg = "0.1.11"
bytesize = "1.3.2"
lazy_static = "1.5.0"
rand = "0.9.0"
rand_distr = "0.5.0"
rustix = { version = "1.0.5", features = ["mm"] }
thousands = "0.2.0"

[target.'cfg(target_vendor="apple")'.dependencies]
mach-sys = "0.5"

# xxx remove unused deps

[profile.release]
lto = "fat"
rustflags = ["-C", "target-cpu=native"]

[lib]
name = "smalloc"
crate-type = ["rlib"]

[[bin]]
name = "testsmalloc"
path = "src/testsmalloc.rs"

