cargo-features = ["profile-rustflags"]

[package]
name = "smalloc"
version = "0.1.2"
edition = "2024"

[dependencies]
bytesize = "1.3.2"
memmapix = "0.7.6"
rand = "0.9.0"
rand_distr = "0.5.0"
thousands = "0.2.0"

[profile.release]
lto = "fat"
rustflags = ["-C", "target-cpu=native"]

[lib]
name = "smalloc"
crate-type = ["rlib"]

[[bin]]
name = "experiments"
path = "src/experiments.rs"

